name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write # gives the workflow permission to write to pull requests. This is needed to create the welcome comment.
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
